// flow-typed signature: 763cb8ae3ed4a497e902b5b7e66a0499
// flow-typed version: <<STUB>>/@babel/plugin-syntax-export-namespace-from_v^7.2.0/flow_v0.100.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/plugin-syntax-export-namespace-from'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/plugin-syntax-export-namespace-from' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/plugin-syntax-export-namespace-from/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/plugin-syntax-export-namespace-from/lib/index.js' {
  declare module.exports: $Exports<'@babel/plugin-syntax-export-namespace-from/lib/index'>;
}
