// flow-typed signature: f75630951d7f750b1e4265ce6103b0ff
// flow-typed version: <<STUB>>/@nsn/eslint-config_v^0.1.0/flow_v0.100.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@nsn/eslint-config'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@nsn/eslint-config' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@nsn/eslint-config/rules/import' {
  declare module.exports: any;
}

// Filename aliases
declare module '@nsn/eslint-config/index' {
  declare module.exports: $Exports<'@nsn/eslint-config'>;
}
declare module '@nsn/eslint-config/index.js' {
  declare module.exports: $Exports<'@nsn/eslint-config'>;
}
declare module '@nsn/eslint-config/rules/import.js' {
  declare module.exports: $Exports<'@nsn/eslint-config/rules/import'>;
}
